### ISSUE TITLE
Redesign positions without a trip?

### ISSUE THREAD

**Issue by xZise** [espinosaluis/TrackMeViewer#19]
There are basically two questions about this:
1. Why are there positions without a trip assigned to them?
2. And if there is a reason why there are positions without a trip, could we have a special "none" trip?

The reason for this special "none" trip is that it is possible to remove the `FK_Users_ID` in the `positions` table as that could lead to inconsistencies (basically `FK_Users_ID` must be the `FK_Users_ID` of the trip with the ID `FK_Trips_ID` if it's not None).

Another reason I suggest is that I'm working on supporting multiple trips (as suggested in the XDA developers forum) and if all positions are assigned to an actual trip there could be just a list of trips. But if there are positions not assigned to a trip I also need to factor in the user id. So basically there is a list of trips and then there is a list of positions for each user separately.

So at the moment supporting multiple trips works if they are from the same user, but as soon as we want to display multiple trips from multiple users we need some kind of logic to differentiate between the unassigned trips of the different users.

Regarding the second suggestion: My idea was to have a row in the `trips` table where the name is `NULL` for example. Then the queries to get the unassigned positions would change from:

```
SELECT * FROM positions WHERE FK_Trips_ID = NULL
```

to

```
SELECT positions.*, trips.FK_Users_ID as FK_Users_ID FROM positions
JOIN trips ON positions.FK_Trips_ID = trips.ID
WHERE trips.Name = NULL
```

**Comment by espinosaluis** [comment]
It's there for legacy purposes. The old TrackMe client for Windows Mobile phones didn't have trips back then. For compatibility reasons, I left it there. TrackMe for Android doesn't allow that anymore, and I'm not sure about the WIndows Phone version because I haven't maintained it for a long time. 

The database that I have for my users had more than 50 million position records and many of them had a null value in the FK_Trips_ID column. Unfortunately recently the database crashed and my host wasn't able to restore it, so we lost all that. Now, the records I have (I just checked) there are not any positions with an empty value in the FK_Trips_ID column. It seems that only a few people are still using a Windows Mobile phone, or they always specify a trip name when they are tracking.
Even though, I would rather leave as it is, so I keep it fully compatible the Android, Windows Phone and Windows Mobile versions, even if the last one is probably hardly used.

I agree with you, and if I could I would get rid of the FK_Users_ID column in the Positions table, and also do not allow nulls in the FK_Trips_ID but I'm afraid we will have to leave it like it is now for legacy purposes because I don't maintain the Windows Phone and the Windows Mobile versions anymore.

**Comment by espinosaluis** [comment]
By the way, I found a bug. When you delete a route, the route list gets empty and you need to logout and login again to see them.

**Comment by xZise** [comment]
Now it's your repository and you can do whatever you want but I'd suggest opening a new issue when you found one to have the issues separated.

**Comment by espinosaluis** [comment]
I mentioned that because it was working before your changes. I can open a new issue if that's easier for you.

**Comment by xZise** [comment]
It easier, because then I could as you how you did delete a trip and it wouldn't be hidden in another unrelated bug ;)
