### ISSUE TITLE
Refreshing route list when a route is deleted.

### ISSUE THREAD

**Issue by espinosaluis** [espinosaluis/TrackMeViewer#22]
When deleting a route, the route list gets emptied and you need to logout and login again to see them.

**Comment by xZise** [comment]
How did you delete the route?

**Comment by espinosaluis** [comment]
There is a small "X" next to the route name.

**Comment by xZise** [comment]
Okay I tried it locally on my test instance and I was able to delete trips (I first needed to set the file permissions correctly because I'm using SQLite). Unfortunately I don't know how I'm going to test this with a MySQL instance. But in worst case scenario the PDO driver isn't able to do changes… (similar to my issues).

**Comment by xZise** [comment]
Also tried now with a MySQL instance and there it worked too so I'm not sure if that was fixed or whether it was actually broken.
