### ISSUE TITLE
When showing a route, the bearings are always displayed by default.

### ISSUE THREAD

**Issue by espinosaluis** [espinosaluis/TrackMeViewer#29]
And even if you uncheck them, they will show up again when you select a different route.
It seems that it's not saving its state.

**Comment by xZise** [comment]
Well it doesn't really store whether bearings are shown. So if you open a new tab and enter the URL without a parameter defining whether the bearings are shown, it should use the configuration setting.

And that I cannot reproduce with the master installation from before your rollback: It is using the value from `config.php` by default.

Now I can change that by using the config window and when I change the trip after that on my test instance it really doesn't save that setting. But to be honest I don't know why my changes would have caused that. So I tried it on your test instance and added points with an angle and the same issue happened: I needed to enable bearings using the config and after selecting another trip it reset that value. (Not sure if that was known to you but #23 mentioned this issue together with other issues my patches actually broke)

And as this is no new issue I think the proper solution would be to store the settings in the database so they are persistent. Another prerequisite might be then that, if the map is publicly available, the logged in user and watched user can be different (so it's not using the settings of the watched but watching user).

**Comment by xZise** [comment]
Okay I figured out the issue and can provide a patch for that although I don't want to include it in #38 so you can make sure everything else works and you don't have to revert everything (that is the reason I provide changes separately).

The issue is that it only uses the configuration values if the `custom_view` parameter is set, but that is never extracted from the requests. So when you enabled the bearings it didn't set that the custom configuration was enabled and thus in the next step it ignored that value. Not sure why this is actually necessary but the fix is pretty simple so we don't have to wait for an improving patch.
